# Generated by Django 5.0.3 on 2024-07-04 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('menu', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('memo', models.TextField(null=True)),
                ('category', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.address')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, null=True)),
                ('open', models.DateTimeField(null=True)),
                ('close', models.DateTimeField(null=True)),
                ('b_start', models.DateTimeField(null=True)),
                ('b_end', models.DateTimeField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.address')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.place')),
            ],
        ),
    ]
