# Generated by Django 5.0.6 on 2024-07-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesshour',
            name='address',
        ),
        migrations.AddField(
            model_name='businesshour',
            name='dayoff',
            field=models.BooleanField(default=False),
        ),
    ]
