# Generated by Django 5.0.6 on 2024-07-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_businesshour_address_businesshour_dayoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshour',
            name='b_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='b_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='close',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='open',
            field=models.TimeField(null=True),
        ),
    ]
