# Generated by Django 5.0.6 on 2024-07-08 10:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        ('search', '0003_alter_businesshour_b_end_alter_businesshour_b_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='address',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 8, 10, 54, 6, 804638)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.place'),
        ),
    ]
