# Generated by Django 5.0.6 on 2024-07-05 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        ('search', '0003_alter_businesshour_b_end_alter_businesshour_b_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='quickslot',
            name='address',
        ),
        migrations.AddField(
            model_name='mypin',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='search.place'),
        ),
        migrations.AddField(
            model_name='quickslot',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='search.place'),
        ),
    ]
