# Generated by Django 5.0.7 on 2024-07-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_list_private_quickslot_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='memo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
