# Generated by Django 5.0.7 on 2024-07-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0006_listlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
